#!/usr/bin/env python3
"""
verify.py - One-command reproducibility harness for the Blue Thumb chloride
validation manuscript (paper/main_v2.tex).

Recomputes every headline claim in the paper directly from committed data and
fails loudly on any mismatch. Run it with:

    python verify.py

It prints a PASS/FAIL table (claim, expected, computed, tolerance, status) and
exits non-zero if ANY check fails.

Design notes
------------
- EXPECTED values are the numbers the manuscript itself states. Each constant
  below carries a comment citing where it appears in paper/main_v2.tex (line
  numbers are from the version committed alongside this script).
- Everything is recomputed from files committed to the repository:
    * data/outputs/phase2_lme/replicate_diffs.csv      (precision; derived)
    * data/outputs/phase2_lme/coverage_distances.csv   (coverage; derived)
    * data/outputs/phase2_lme/historical_qa_results_corrected.csv (accuracy)
    * data/outputs/phase2_lme/lme_analysis_df.csv      (GLMM, subsampling, VIF, overlap)
  No raw / gitignored data file is required to run this verifier.
- The two derived files are regenerated by scripts/generate_verification_data.py
  from the raw sources; that step is part of the full-reproduction path and is
  documented in QUICKSTART.md.
- Subsampling (claim 4) runs a seeded 200-draw set here for speed (~1-2 min) and
  asserts the non-significant fraction exceeds 0.95. The full 1,000-seed run
  (scripts/stratified_subsampling.py) gives 98.6 percent; see output note.

Total runtime target: about 1-3 minutes.
"""

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.simplefilter("ignore")  # statsmodels convergence chatter; we record fits explicitly

# ---------------------------------------------------------------------------
# Paths (all committed)
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent
PHASE2 = ROOT / "data" / "outputs" / "phase2_lme"
REPLICATE_DIFFS = PHASE2 / "replicate_diffs.csv"
COVERAGE_DISTANCES = PHASE2 / "coverage_distances.csv"
QA_ACCURACY = PHASE2 / "historical_qa_results_corrected.csv"
LME_DF = PHASE2 / "lme_analysis_df.csv"

# ---------------------------------------------------------------------------
# EXPECTED values from paper/main_v2.tex (manuscript-stated numbers).
# Each comment cites the line(s) where the value appears.
# ---------------------------------------------------------------------------

# Claim 1: Precision (Table, lines 201-203; abstract line 23; text line 209)
EXP_VOL_WITHIN_1_DROP_PCT = 97.3      # "97.3\% of pairs agree within one drop" (lines 23, 209, 315)
EXP_VOL_MEAN_DIFF = 1.53              # volunteer mean |diff| mg/L (lines 23, 201, 209)
EXP_VOL_N = 2566                      # N=2,566 volunteer replicate pairs (lines 23, 154, 201)
EXP_VOL_PCT_IDENTICAL = 73.2         # 73.2\% identical (lines 209, 315)
EXP_VOL_PCT_1DROP = 24.1            # 24.1\% differ by one drop (line 209)
EXP_PRO_WT_MEAN_DIFF = 2.51          # professional within-test mean |diff| (lines 23, 202, 209)
EXP_PRO_WT_N = 113                    # N=113 churn-splitter duplicate pairs (lines 112, 155, 202)
EXP_PRO_WS_MEAN_DIFF = 3.58          # professional within-site mean |diff| (line 203)
EXP_PRO_WS_N = 114                    # N=114 spatial replicate pairs (lines 112, 156, 203)

# Claim 2: Accuracy (Table lines 227-229; text lines 23, 234; provenance line 124)
EXP_ACC_N = 867                       # 867 individual indoor QA tests (lines 23, 124, 164)
EXP_ACC_LOW_MEAN = 4.37             # low tier (<=50) mean error mg/L (line 227)
EXP_ACC_MID_MEAN = 5.32             # mid tier (50-100) mean error mg/L (line 228)
EXP_ACC_HIGH_MEAN = 32.20           # high tier (>100) mean error mg/L (line 229)
EXP_ACC_N_LE_100 = 603             # "603 of 867 tests" at <=100 mg/L (line 234)

# Claim 3: Regional GLMM (Table lines 249-260; abstract line 23; text line 264)
EXP_GLMM_BETA = -0.433              # IsVolunteer beta (lines 23, 252, 264)
EXP_GLMM_SE = 0.218                 # IsVolunteer SE (line 252)
EXP_GLMM_P = 0.047                  # IsVolunteer p-value (lines 23, 252, 264)
EXP_GLMM_N = 895                    # N=895 observations (lines 128, 245, 260)
EXP_GLMM_SITES = 92                # 92 sites (lines 128, 245, 260)

# Claim 4: Stratified subsampling (text lines 286-291; abstract line 23)
EXP_SUB_FRAC_NONSIG = 0.986        # non-significant in 98.6\% of balanced subsamples (line 291)
EXP_SUB_MEDIAN_P = 0.48           # median p approx 0.48 (lines 23 implies, 286, 291)
SUB_FRAC_NONSIG_FLOOR = 0.95      # this verifier asserts fraction > 0.95 on a fast 200-draw run

# Claim 5: Identifiability (text line 264)
EXP_VIF = 1.29                     # VIF(IsVolunteer ~ Longitude + seasonal) approx 1.29 (line 264)
EXP_SITES_BOTH_TYPES = 0          # 0 of 92 sites contain both observer types (line 264)

# Claim 6: Coverage (text lines 21, 36, 78, 300, 371)
EXP_COV_PCT_FAR = 93.0           # 93\% of sites > 1 km from nearest professional (lines 21, 78, 300)
EXP_COV_N_SITES = 327            # 327 unique volunteer chloride monitoring sites (lines 21, 78, 299)
EXP_COV_N_FAR = 305            # "93\% (305 sites)" > 1 km (line 300); Haversine
EXP_COV_N_FAR5 = 196           # "60\% (196 sites)" > 5 km (line 301)
EXP_COV_N_FAR10 = 90           # "28\% (90 sites)" > 10 km (line 302)

# Subsampling run parameters for the fast verification path
SUB_N_ITER = 200
SUB_SEED = 42
SUB_FORMULA = "LogChloride ~ IsVolunteer + JulianSin + JulianCos + Longitude"


# ---------------------------------------------------------------------------
# Result collection
# ---------------------------------------------------------------------------
class Check:
    def __init__(self, name, expected, computed, tol, status, note=""):
        self.name = name
        self.expected = expected
        self.computed = computed
        self.tol = tol
        self.status = status
        self.note = note


RESULTS = []


def record(name, expected, computed, tol, *, exact=False, note=""):
    """Compare computed vs expected within tol and record a Check.

    exact=True compares integers/counts exactly (tol shown as 0).
    """
    if exact:
        ok = int(round(computed)) == int(round(expected))
        tol_disp = "exact"
    else:
        ok = abs(computed - expected) <= tol
        tol_disp = f"+/-{tol:g}"
    RESULTS.append(
        Check(name, expected, computed, tol_disp, "PASS" if ok else "FAIL", note)
    )
    return ok


def require(path):
    if not path.exists():
        print(f"FATAL: required committed file not found: {path}", file=sys.stderr)
        print("Run scripts/generate_verification_data.py first (see QUICKSTART.md).",
              file=sys.stderr)
        sys.exit(2)


# ---------------------------------------------------------------------------
# Claim 1: Precision
# ---------------------------------------------------------------------------
def check_precision():
    require(REPLICATE_DIFFS)
    df = pd.read_csv(REPLICATE_DIFFS)

    vol = df[df["group"] == "volunteer_within_test"].copy()
    vol_drop = vol["drop_diff"].astype(float)
    n_vol = len(vol)
    mean_vol = vol["abs_diff_mgL"].mean()
    pct_identical = 100.0 * (vol_drop == 0).mean()
    pct_1drop = 100.0 * (vol_drop == 1).mean()
    pct_within_1 = 100.0 * (vol_drop <= 1).mean()

    pro_wt = df[df["group"] == "professional_within_test"]["abs_diff_mgL"]
    pro_ws = df[df["group"] == "professional_within_site"]["abs_diff_mgL"]

    record("1. Precision: vol within-1-drop %", EXP_VOL_WITHIN_1_DROP_PCT, pct_within_1, 0.2)
    record("1. Precision: vol mean |diff| mg/L", EXP_VOL_MEAN_DIFF, mean_vol, 0.02)
    record("1. Precision: vol N pairs", EXP_VOL_N, n_vol, 0, exact=True)
    record("1. Precision: vol % identical", EXP_VOL_PCT_IDENTICAL, pct_identical, 0.2)
    record("1. Precision: vol % one drop", EXP_VOL_PCT_1DROP, pct_1drop, 0.2)
    record("1. Precision: pro within-test mean", EXP_PRO_WT_MEAN_DIFF, pro_wt.mean(), 0.02)
    record("1. Precision: pro within-test N", EXP_PRO_WT_N, len(pro_wt), 0, exact=True)
    record("1. Precision: pro within-site mean", EXP_PRO_WS_MEAN_DIFF, pro_ws.mean(), 0.02)
    record("1. Precision: pro within-site N", EXP_PRO_WS_N, len(pro_ws), 0, exact=True)


# ---------------------------------------------------------------------------
# Claim 2: Accuracy (volunteers read high)
# ---------------------------------------------------------------------------
def check_accuracy():
    require(QA_ACCURACY)
    df = pd.read_csv(QA_ACCURACY)
    n = len(df)
    low = df[df["Known_Standard"] <= 50]
    mid = df[(df["Known_Standard"] > 50) & (df["Known_Standard"] <= 100)]
    high = df[df["Known_Standard"] > 100]
    n_le100 = len(low) + len(mid)

    record("2. Accuracy: N tests", EXP_ACC_N, n, 0, exact=True)
    record("2. Accuracy: low tier mean err", EXP_ACC_LOW_MEAN, low["Difference"].mean(), 0.05)
    record("2. Accuracy: mid tier mean err", EXP_ACC_MID_MEAN, mid["Difference"].mean(), 0.05)
    record("2. Accuracy: high tier mean err", EXP_ACC_HIGH_MEAN, high["Difference"].mean(), 0.05)
    record("2. Accuracy: N tests <=100 mg/L", EXP_ACC_N_LE_100, n_le100, 0, exact=True)

    # Direction: every tier mean error must be positive (volunteers read HIGH).
    all_positive = (low["Difference"].mean() > 0
                    and mid["Difference"].mean() > 0
                    and high["Difference"].mean() > 0)
    RESULTS.append(Check(
        "2. Accuracy: every tier reads high (>0)",
        "all > 0",
        f"low={low['Difference'].mean():.2f}, mid={mid['Difference'].mean():.2f}, "
        f"high={high['Difference'].mean():.2f}",
        "sign",
        "PASS" if all_positive else "FAIL",
    ))


# ---------------------------------------------------------------------------
# Claims 3, 5: Regional GLMM and identifiability (VIF, overlap)
# ---------------------------------------------------------------------------
def _prep_lme(df):
    df = df.copy()
    df["IsVolunteer"] = (df["ObserverType"] == "Volunteer").astype(int)
    df["LogChloride"] = np.log(df["Chloride_mgL"])
    return df


def check_glmm_and_identifiability():
    require(LME_DF)
    import statsmodels.api as sm
    import statsmodels.formula.api as smf
    from statsmodels.regression.linear_model import OLS

    df = _prep_lme(pd.read_csv(LME_DF))
    n = len(df)
    n_sites = df["Site"].nunique()

    m = smf.mixedlm(SUB_FORMULA, data=df, groups=df["Site"]).fit(reml=True)
    beta = m.params["IsVolunteer"]
    se = m.bse["IsVolunteer"]
    p = m.pvalues["IsVolunteer"]

    record("3. GLMM: IsVolunteer beta", EXP_GLMM_BETA, beta, 0.005)
    record("3. GLMM: IsVolunteer SE", EXP_GLMM_SE, se, 0.005)
    record("3. GLMM: IsVolunteer p", EXP_GLMM_P, p, 0.002)
    record("3. GLMM: N observations", EXP_GLMM_N, n, 0, exact=True)
    record("3. GLMM: N sites", EXP_GLMM_SITES, n_sites, 0, exact=True)

    # VIF of IsVolunteer regressed on Longitude + seasonal harmonics.
    X = sm.add_constant(df[["Longitude", "JulianSin", "JulianCos"]])
    r2 = OLS(df["IsVolunteer"], X).fit().rsquared
    vif = 1.0 / (1.0 - r2)
    record("5. Identifiability: VIF(IsVol~Lon+seasonal)", EXP_VIF, vif, 0.02)

    # Overlap: number of sites with both observer types must be 0.
    sites_both = int((df.groupby("Site")["ObserverType"].nunique() > 1).sum())
    record("5. Identifiability: sites with both types", EXP_SITES_BOTH_TYPES,
           sites_both, 0, exact=True)


# ---------------------------------------------------------------------------
# Claim 4: Stratified subsampling (geographic confound test)
# ---------------------------------------------------------------------------
def check_subsampling():
    require(LME_DF)
    import statsmodels.formula.api as smf

    df = _prep_lme(pd.read_csv(LME_DF))
    pro = df[df.IsVolunteer == 0]
    vol = df[df.IsVolunteer == 1]
    vol_sites = vol.groupby("Site")["Longitude"].mean().reset_index()
    vol_sites["quartile"] = pd.qcut(vol_sites["Longitude"], 4, labels=False)

    rng = np.random.default_rng(SUB_SEED)
    ps = []
    fails = 0
    for _ in range(SUB_N_ITER):
        picks = []
        for q in range(4):
            sites_q = vol_sites.loc[vol_sites.quartile == q, "Site"].to_numpy()
            picks += list(rng.choice(sites_q, size=min(3, len(sites_q)), replace=False))
        sub = pd.concat([pro, vol[vol.Site.isin(picks)]], ignore_index=True)
        try:
            m = smf.mixedlm(SUB_FORMULA, data=sub, groups=sub["Site"]).fit(reml=True)
            ps.append(m.pvalues["IsVolunteer"])
        except Exception:
            fails += 1

    ps = np.array(ps)
    frac_nonsig = float(np.mean(ps >= 0.05))
    median_p = float(np.median(ps))

    # Primary assertion: fraction non-significant must exceed the floor.
    ok = frac_nonsig > SUB_FRAC_NONSIG_FLOOR
    RESULTS.append(Check(
        f"4. Subsampling: frac non-sig ({len(ps)} draws)",
        f"> {SUB_FRAC_NONSIG_FLOOR:.2f}",
        f"{frac_nonsig:.3f}",
        f"> {SUB_FRAC_NONSIG_FLOOR:.2f}",
        "PASS" if ok else "FAIL",
        f"full 1000-seed run = {EXP_SUB_FRAC_NONSIG:.3f}; {fails} fits failed",
    ))
    # Secondary: median p in the expected neighborhood of 0.48.
    record("4. Subsampling: median p", EXP_SUB_MEDIAN_P, median_p, 0.08,
           note="paper reports median p approx 0.48")


# ---------------------------------------------------------------------------
# Claim 6: Coverage
# ---------------------------------------------------------------------------
def check_coverage():
    require(COVERAGE_DISTANCES)
    df = pd.read_csv(COVERAGE_DISTANCES)
    n_sites = len(df)
    n_far = int((df["nearest_professional_km"] > 1.0).sum())
    n_far5 = int((df["nearest_professional_km"] > 5.0).sum())
    n_far10 = int((df["nearest_professional_km"] > 10.0).sum())
    pct_far = 100.0 * n_far / n_sites

    record("6. Coverage: N volunteer sites", EXP_COV_N_SITES, n_sites, 0, exact=True)
    record("6. Coverage: N sites > 1 km", EXP_COV_N_FAR, n_far, 0, exact=True)
    record("6. Coverage: % sites > 1 km", EXP_COV_PCT_FAR, pct_far, 0.5)
    record("6. Coverage: N sites > 5 km", EXP_COV_N_FAR5, n_far5, 0, exact=True)
    record("6. Coverage: N sites > 10 km", EXP_COV_N_FAR10, n_far10, 0, exact=True)


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------
def print_table():
    name_w = max(len(r.name) for r in RESULTS)
    name_w = max(name_w, len("CLAIM CHECK"))
    exp_w = max(max(len(str(r.expected)) for r in RESULTS), len("EXPECTED"))
    com_w = max(max(len(str(r.computed)) for r in RESULTS), len("COMPUTED"))

    def fmt(v):
        if isinstance(v, float):
            return f"{v:.4f}"
        return str(v)

    header = (f"{'CLAIM CHECK':<{name_w}}  {'EXPECTED':>{exp_w}}  "
              f"{'COMPUTED':>{com_w}}  {'TOL':>8}  STATUS")
    print(header)
    print("-" * len(header))
    for r in RESULTS:
        exp = fmt(r.expected)
        com = fmt(r.computed)
        mark = "PASS" if r.status == "PASS" else "FAIL <<<"
        line = (f"{r.name:<{name_w}}  {exp:>{exp_w}}  {com:>{com_w}}  "
                f"{r.tol:>8}  {mark}")
        print(line)
        if r.note:
            print(f"{'':<{name_w}}  -> {r.note}")


def main():
    print("=" * 78)
    print("Blue Thumb chloride manuscript - reproducibility verification (verify.py)")
    print("Recomputing all six headline claims from committed data.")
    print("=" * 78)
    print()

    check_precision()
    check_accuracy()
    print("Fitting regional GLMM and identifiability metrics ...")
    check_glmm_and_identifiability()
    print(f"Running {SUB_N_ITER} seeded stratified subsamples (this is the slow step) ...")
    check_subsampling()
    check_coverage()

    print()
    print_table()
    print()

    n_fail = sum(1 for r in RESULTS if r.status != "PASS")
    n_pass = len(RESULTS) - n_fail
    print("=" * 78)
    if n_fail == 0:
        print(f"ALL CHECKS PASSED ({n_pass}/{len(RESULTS)}). "
              "Every headline claim reproduces from committed data.")
        print("Note: claim 4 uses a fast 200-draw subsample here; the full 1,000-seed")
        print("run (scripts/stratified_subsampling.py 1000 42) gives 98.6% non-significant.")
        print("=" * 78)
        sys.exit(0)
    else:
        print(f"VERIFICATION FAILED: {n_fail} of {len(RESULTS)} checks did not reproduce.")
        print("=" * 78)
        sys.exit(1)


if __name__ == "__main__":
    main()
